name: GitHub Actions Demo

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches:
      - main

env:
  BASE_URL: https://raw.githubusercontent.com/MarlinFirmware/Configurations/release-2.1.2/config/examples/
  FQ_BOARD_PATH: Creality/Ender-3%20Pro/CrealityV422


jobs:
  Build-Marlin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out Marlin Repo
        uses: actions/checkout@v3
        with:
          repository: 'MarlinFirmware/Marlin'
          ref: '2.1.x'
          token: ${{ github.token }}
          path: 'marlin'
      # - name: Checkout out MarlinBuilder repo
      #   uses: actions/checkout@v3
      #   with:
      #     path: 'main'
      # - run: ls main
      - run: ls marlin
      - name: Replace processor architecture name
        run: sed -i 's/mega2560/STM32F103RE_creality/' marlin/platformio.ini
      - name: Print INI file
        run: cat marlin/platformio.ini
      - name: Remove default config files
        run: rm marlin/Marlin/Configuration*
      - name: Get specific config files
        working-directory: marlin/Marlin/
        run: |
          wget "${BASE_URL}${FQ_BOARD_PATH}/_Bootscreen.h" 
          wget "${BASE_URL}${FQ_BOARD_PATH}/_Statusscreen.h" 
          wget "${BASE_URL}${FQ_BOARD_PATH}/Configuration.h" 
          wget "${BASE_URL}${FQ_BOARD_PATH}/Configuration_adv.h" 
      # - name: Cache pip
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.cache/pip
      #   key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      #   restore-keys: |
      #     ${{ runner.os }}-pip-
      # - name: Cache PlatformIO
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.platformio
      #     key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Select Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: '3.7' # Version range or exact version of a Python version to use, using semvers version range syntax.
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Install PlatformIO
        run: |
          pip install -U platformio
          pio upgrade --dev
          pio pkg update --global
      - name: Build Firmware
        working-directory: marlin
        run: |
          platformio run
