name: GitHub Actions Demo

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches:
      - main

env:
  BASE_URL: https://raw.githubusercontent.com/MarlinFirmware/Configurations/release-2.1.2.1/config/examples/
  FQ_BOARD_PATH: Creality/Ender-3%20Pro/CrealityV422


jobs:
  Build-Marlin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out Marlin Repo
        uses: actions/checkout@v3
        with:
          repository: 'MarlinFirmware/Marlin'
          ref: '2.1.2.1'
          token: ${{ github.token }}
          path: 'marlin'
      - run: ls marlin
      - name: Replace processor architecture name
        run: sed -i 's/mega2560/STM32F103RE_creality/' marlin/platformio.ini
      - name: Print INI file
        run: cat marlin/platformio.ini
      - name: Remove default config files
        run: rm marlin/Marlin/Configuration*
      - name: Get specific config files
        working-directory: marlin/Marlin/
        run: |
          wget "${BASE_URL}${FQ_BOARD_PATH}/_Bootscreen.h" 
          wget "${BASE_URL}${FQ_BOARD_PATH}/_Statusscreen.h" 
          wget "${BASE_URL}${FQ_BOARD_PATH}/Configuration.h" 
          wget "${BASE_URL}${FQ_BOARD_PATH}/Configuration_adv.h" 
      - name: Enable Host Action Commands
        working-directory: marlin/Marlin/
        run: |
          sed -i 's|//#define HOST_ACTION_COMMANDS|#define HOST_ACTION_COMMANDS|' Configuration_adv.h          
          cat Configuration_adv.h
      - name: Select Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install PlatformIO
        run: |
          pip install -U platformio
          pio upgrade --dev
          pio pkg update --global
      - name: Build Firmware
        working-directory: marlin
        run: |
          platformio run
      # - name: Get Binary Filename
      #   working-directory: marlin/.pio/build/STM32F103RE_creality
      #   run: |
      #     FILENAME=$(ls *bin)
      #     echo $FILENAME
      # - name: Copy Firmware build
      #   run: |
      #     cp marlin/.pio/build/STM32F103RE_creality/firmware*bin ~/firmwares
      - name: Copy Firmware over SSH
        uses: nogsantos/scp-deploy@master
        with: 
          src: marlin/.pio/build/STM32F103RE_creality/firmware*bin
          host: ${{ secrets.HOST }}
          remote: ${{ secrets.REMOTE }}
          port: ${{ secrets.PORT }}
